from __future__ import annotations

from typing import Any, Protocol, Tuple


class BackendOps(Protocol):
    """Protocol defining the tensor operations TurboQuant needs."""

    def randn(self, shape: Tuple[int, ...], seed: int) -> Any: ...
    def qr(self, matrix: Any) -> Tuple[Any, Any]: ...
    def matmul(self, a: Any, b: Any) -> Any: ...
    def transpose(self, a: Any) -> Any: ...
    def norm(self, x: Any, dim: int, keepdim: bool = False) -> Any: ...
    def abs(self, x: Any) -> Any: ...
    def argmin(self, x: Any, dim: int) -> Any: ...
    def index_select(self, table: Any, indices: Any) -> Any: ...
    def unsqueeze(self, x: Any, dim: int) -> Any: ...
    def concat(self, arrays: list, dim: int) -> Any: ...
    def zeros(self, shape: Tuple[int, ...]) -> Any: ...
    def from_numpy(self, arr: Any) -> Any: ...
    def to_numpy(self, x: Any) -> Any: ...
    def float32(self, x: Any) -> Any: ...
    def float16(self, x: Any) -> Any: ...
    def uint8(self, x: Any) -> Any: ...
    def int64(self, x: Any) -> Any: ...
    def sign(self, x: Any) -> Any: ...
